### ISSUE TITLE
Question: Is there any reason to archive the Result CallAdapter before?

### ISSUE THREAD

**Issue by Goooler** [connyduck/networkresult-calladapter#12]
I see you archived https://github.com/connyduck/calladapter and migrated to this lib, is there any reason to do so? 

Maybe we can mention deprecation in that lib and suggest users move to this.

**Comment by connyduck** [comment]
`kotlin.Result` is a value class and did not work correctly in all cases with the runtime tye checks required for retrofit, causing crashes.

I added a warning and a link to the new project to the old one.

**Comment by Goooler** [comment]
`Result` support in Retrofit will be finished in https://github.com/square/retrofit/pull/4018, it would be great if you can take a review.

**Comment by connyduck** [comment]
Oh `Result` support directly in retrofit would be way better than a custom adapter
